baseURL = "https://example.org/"
title = "Inyo 陰陽"
defaultContentLanguage = "zh-cn"
enableRobotsTXT = true

[languages.zh-cn]
label = "中文"
locale = "zh-CN"
weight = 1

[module]
[[module.imports]]
path = "github.com/FeiNiaoBF/hugo-theme-inyo"

[params]
subtitle = "纸墨二元 · 落字有间"
author = "Inyo"

[markup]
_merge = "deep"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true

[[params.social]]
name = "GitHub"
url = "https://github.com/FeiNiaoBF/hugo-theme-inyo"

[[params.social]]
name = "RSS"
url = "/index.xml"
