baseURL = "https://example.org/"
title = "Inyo 陰陽 · Demo"
locale = "zh-cn"
defaultContentLanguage = "zh-cn"
enableRobotsTXT = true

[module]
[[module.imports]]
path = "github.com/FeiNiaoBF/hugo-theme-inyo"

[params]
math = true
seal_text = "陰陽"
seal_style = "yang"
